@startuml ViewJourneyDetailsSequenceDiagram
skinparam BackgroundColor #ffffff
skinparam sequence {
    LifeLineBorderColor #000000
    LifeLineBackgroundColor #7acff5
    ParticipantBackgroundColor #7acff5
    ParticipantBorderColor #000000
    ActorBackgroundColor #7acff5
    ActorBorderColor #000000
    ArrowColor #000000
    SequenceBoxBackgroundColor #7acff5
}

actor "Driver/Passenger" as User
participant "Android App" as App
participant "Backend Module" as Backend
participant "Database" as DB

User -> App : 1: Click on a Specific Journey on Journey List
activate App

App -> Backend : 1.1: Fetch Journey Details (journeyID)
activate Backend

Backend -> DB : 1.1.1: Query Journey Details by journeyID
activate DB
DB --> Backend : 1.1.1.1: Return Journey Details
deactivate DB

Backend --> App : 1.2: Send Journey Details
deactivate Backend

App -> User : 1.3: Display Journey Details Screen

deactivate App

@enduml
