@startuml CreateAssetClassDiagram

title Create Asset Class Diagram
skinparam classAttributeIconSize 0
skinparam linetype ortho

package pkgFragmentAssets {

    ' Main Fragment
    class AssetFragment {
        + onCreateView(): void
        + onClickCreateAssetButton(): void
        + onCaptureButtonClick(): void
        + onCloseOverlay(): void
        + startPermissionService(): void
    }

    ' Permission Management Service
    class AssetService {
        + requestRecordingPermission(): void
        + activateOverlay(): void
    }

    ' Camera Overlay Logic
    class CameraOverlay {
        + showOverlay(): void
        + hideOverlay(): void
        + captureImage(): void
    }
}

' Relationships
AssetFragment --> AssetService
AssetService --*CameraOverlay 


@enduml
