@startuml CreateAssetSequenceDiagram

title Create Asset Sequence Diagram
actor User
participant AssetFragment
participant AssetService
participant CameraOverlay
participant UserDevice

User -> AssetFragment : Launch Fragment
activate AssetFragment

AssetFragment -> AssetFragment : onCreateView()

User -> AssetFragment : Click Create Asset Button
AssetFragment -> AssetService : activateOverlay()
activate AssetService
AssetService -> CameraOverlay : showOverlay()
activate CameraOverlay
    User -> CameraOverlay : Click Capture Button
    CameraOverlay -> UserDevice : Capture Image
    activate UserDevice
    UserDevice --> CameraOverlay : Image Captured
    deactivate UserDevice
    CameraOverlay -> AssetService : Notify Capture Complete
    deactivate CameraOverlay
    AssetService -> AssetFragment : Asset Created

    User -> CameraOverlay : Press Stop Button
    activate CameraOverlay
    AssetFragment <-- CameraOverlay : hideOverlay()
    deactivate CameraOverlay
deactivate AssetService
deactivate AssetFragment

@enduml
