@startuml UpdateCategoryDocumentClassDiagram
skinparam classAttributeIconSize 0
skinparam linetype ortho
Title Update CategoryDocument Class Diagram
'Character	Visibility
'-			private
'#			protected
'~			package private
'+			public

'Extension	<|--	Quan hệ mở rộng từ (là extends hoặc implements nhưng ko có annotations trong code)
'Composition	*--	 Quan hệ gắn kết chặt chẽ : part - of
'Aggregation	o--	Quan hệ liên kết giữa hai thực thể : use, has

' Include các file vào trong file để sử dụng'

package pkgUpdateCategoryDocument <<Frame>> {  
    'include controller'
    !includesub ../../ControllersClassDiagram.plantuml!CategoryDocumentsController
    !includesub ../../ControllersClassDiagram.plantuml!ControllerBase
    !includesub ../../ControllersClassDiagram.plantuml!AdminAuthorizationAttribute

    
    'include Repository'
    !includesub ../../RepositoriesClassDiagram.plantuml!IRepositoryBase
    !includesub ../../RepositoriesClassDiagram.plantuml!RepositoryBase
    !includesub ../../RepositoriesClassDiagram.plantuml!DbContext
    !includesub ../../RepositoriesClassDiagram.plantuml!InSyncContext
    !includesub ../../RepositoriesClassDiagram.plantuml!ICategoryDocumentRepository
    !includesub ../../RepositoriesClassDiagram.plantuml!CategoryDocumentRepository
    'include Dto'
    !includesub ../../DtosClassDiagram.plantuml!UpdateCategoryDocumentDto
    !includesub ../../ModelsClassDiagram.plantuml!CategoryDocument


    'set up realation ship' 
    ControllerBase <|-- CategoryDocumentsController

    CategoryDocumentsController ..> UpdateCategoryDocumentDto : Input Update CategoryDocument

    IRepositoryBase <|.. RepositoryBase
    ICategoryDocumentRepository <|.. CategoryDocumentRepository
    CategoryDocumentRepository o-- CategoryDocument


    IRepositoryBase <|-- ICategoryDocumentRepository 
    RepositoryBase <|-- CategoryDocumentRepository


    DbContext <|--InSyncContext
    RepositoryBase o-- InSyncContext
    CategoryDocumentsController o-- ICategoryDocumentRepository
    CategoryDocumentsController o-- IMapper
    CategoryDocumentsController ..> AdminAuthorizationAttribute : use




}