@startuml ExecuteActionSequenceDiagram

title Execute Action Sequence Diagram
actor User
participant ViewScenarioCodeActivity
participant ActionOverlay
participant ExecuteService
participant Scenario
participant UserDevice

User -> ViewScenarioCodeActivity : Launch Activity
activate ViewScenarioCodeActivity

ViewScenarioCodeActivity -> ViewScenarioCodeActivity : onCreate()
ViewScenarioCodeActivity -> ViewScenarioCodeActivity : initializeOverlay()



alt Program Run Normally
    ViewScenarioCodeActivity -> ActionOverlay : showOverlay()
    activate ActionOverlay
    ActionOverlay -> ExecuteService : Trigger Scenario Execution
    activate ExecuteService

    ExecuteService -> Scenario : execute()
    activate Scenario

    ExecuteService -> UserDevice : Interact with Device
    activate UserDevice
    ExecuteService -> ExecuteService : logExecutionDetails(scenario)
    UserDevice --> ExecuteService : Action Complete
    deactivate UserDevice
    ExecuteService -> Scenario : Stop Execution
    Scenario --> ExecuteService : Execution Stopped
    ExecuteService --> ActionOverlay : Execution Complete
    deactivate ActionOverlay
    deactivate Scenario
    deactivate ExecuteService
else User Presses Stop Button
    ViewScenarioCodeActivity -> ActionOverlay : showOverlay()
    activate ActionOverlay
    ActionOverlay -> ExecuteService : Trigger Scenario Execution
    activate ExecuteService

    ExecuteService -> Scenario : execute()
    activate Scenario

    ExecuteService -> UserDevice : Interact with Device
    activate UserDevice
    ExecuteService -> ExecuteService : logExecutionDetails(scenario)
    UserDevice --> ExecuteService : Action Complete
    deactivate UserDevice
    User -> ActionOverlay : Press Stop Button
    ActionOverlay -> ExecuteService : Cancel Execution
    ExecuteService --> Scenario : Stop Execution
    Scenario --> ExecuteService : Execution Stopped
    deactivate Scenario
    ExecuteService --> ActionOverlay : Execution Stopped
    
    deactivate ExecuteService
end

ActionOverlay --> ViewScenarioCodeActivity : hideOverlay()
deactivate ActionOverlay
deactivate ViewScenarioCodeActivity

@enduml
