@startuml ExecuteActionClassDiagram

title Execute Action Class Diagram
skinparam classAttributeIconSize 0
skinparam linetype ortho

package "pkgExecuteActionCode" {

    !includesub ../../MobileModelClassDiagram.plantuml!Scenario

    class ViewScenarioCodeActivity {
        + onCreate(): void
        + displayScenarioDetails(scenarioId: String): void
        + initializeOverlay(): void
        + onOverlayButtonClick(): void
    }

    class ActionOverlay {
        + hideOverlay(): void
    }

    class ExecuteService {
        + executeScenario(scenario: Scenario): void
        + logExecutionDetails(scenario: Scenario): void
        + showOverlay(): void
    }
}

' Relationships
ExecuteService ..> Scenario
Scenario --> ViewScenarioCodeActivity : "Details"
ViewScenarioCodeActivity --* ExecuteService : "Initializes"
ActionOverlay <-- ExecuteService : "Show"

@enduml