@startuml ViewMarktingPageClassDiagram
skinparam classAttributeIconSize 0
skinparam linetype ortho

Title View Marketing Pages Class Diagram
'Character	Visibility
'-			private
'#			protected
'~			package private
'+			public

'Extension	<|--	Quan hệ mở rộng từ (là extends hoặc implements nhưng ko có annotations trong code)
'Composition	*--	 Quan hệ gắn kết chặt chẽ : part - of
'Aggregation	o--	Quan hệ liên kết giữa hai thực thể : use, has

' Include các file vào trong file để sử dụng'

package pkgViewMarkting <<Frame>> {  
    'include controller'
    !includesub ../ControllersClassDiagram.plantuml!ControllerBase
    !includesub ../ControllersClassDiagram.plantuml!CategoryDocumentController
    !includesub ../ControllersClassDiagram.plantuml!DocumentsController


    
    'include Repository'
    !includesub ../RepositoriesClassDiagram.plantuml!IRepositoryBase
    !includesub ../RepositoriesClassDiagram.plantuml!RepositoryBase
    !includesub ../RepositoriesClassDiagram.plantuml!DbContext
    !includesub ../RepositoriesClassDiagram.plantuml!InSyncContext
    !includesub ../RepositoriesClassDiagram.plantuml!ICategoryDocumentRepository
    !includesub ../RepositoriesClassDiagram.plantuml!CategoryDocumentRepository
    !includesub ../RepositoriesClassDiagram.plantuml!IDocumentRepository
    !includesub ../RepositoriesClassDiagram.plantuml!DocumentRepository

    'include Dto'
    !includesub ../DtosClassDiagram.plantuml!ViewCategoryDocumentDto
    !includesub ../ModelsClassDiagram.plantuml!CategoryDocument
    !includesub ../DtosClassDiagram.plantuml!ViewDocumentDto
    !includesub ../ModelsClassDiagram.plantuml!Document



    'set up realation ship' 
    ControllerBase <|-- CategoryDocumentController
    ControllerBase <|-- DocumentsController


    CategoryDocumentController ..> ViewCategoryDocumentDto : return views
    DocumentsController ..> ViewDocumentDto : return views
    
    


    IRepositoryBase <|.. RepositoryBase
    ICategoryDocumentRepository <|.. CategoryDocumentRepository
    CategoryDocumentRepository o-- CategoryDocument

    IDocumentRepository <|.. DocumentRepository
    DocumentRepository o-- Document



    IRepositoryBase <|-- ICategoryDocumentRepository 
    RepositoryBase <|-- CategoryDocumentRepository

    IRepositoryBase <|-- IDocumentRepository 
    RepositoryBase <|-- DocumentRepository



    DbContext <|--InSyncContext
    RepositoryBase o-- InSyncContext
    CategoryDocumentController o-- ICategoryDocumentRepository
    DocumentsController o-- IDocumentRepository
   



}