@startuml ViewHomePageClassDiagram
skinparam classAttributeIconSize 0
skinparam linetype ortho
Title ViewHomePage Class Diagram
'Character	Visibility
'-			private
'#			protected
'~			package private
'+			public

'Extension	<|--	Quan hệ mở rộng từ (là extends hoặc implements nhưng ko có annotations trong code)
'Composition	*--	 Quan hệ gắn kết chặt chẽ : part - of
'Aggregation	o--	Quan hệ liên kết giữa hai thực thể : use, has

' Include các file vào trong file để sử dụng'

package pkgViewHomePage <<Frame>> {  
    'include controller'
    !includesub ../ControllersClassDiagram.plantuml!SubscriptionPlansController
    !includesub ../ControllersClassDiagram.plantuml!CustomerReviewsController
    !includesub ../ControllersClassDiagram.plantuml!ControllerBase

    
    'include Repository'
    !includesub ../RepositoriesClassDiagram.plantuml!IRepositoryBase
    !includesub ../RepositoriesClassDiagram.plantuml!RepositoryBase
    !includesub ../RepositoriesClassDiagram.plantuml!DbContext
    !includesub ../RepositoriesClassDiagram.plantuml!InSyncContext
    !includesub ../RepositoriesClassDiagram.plantuml!ISubscriptionPlanRepository
    !includesub ../RepositoriesClassDiagram.plantuml!SubscriptionPlanRepository
    !includesub ../RepositoriesClassDiagram.plantuml!ICustomerReviewRepository
    !includesub ../RepositoriesClassDiagram.plantuml!CustomerReviewRepository
    'include Dto'
    !includesub ../DtosClassDiagram.plantuml!ViewSubscriptionPlanDto
    !includesub ../ModelsClassDiagram.plantuml!SubscriptionPlan
    !includesub ../DtosClassDiagram.plantuml!ViewCustomerReviewDto
    !includesub ../ModelsClassDiagram.plantuml!CustomerReview


    'set up realation ship' 
    ControllerBase <|-- SubscriptionPlansController
    ControllerBase <|-- CustomerReviewsController
    SubscriptionPlansController ..> ViewSubscriptionPlanDto : return views
    CustomerReviewsController ..> ViewCustomerReviewDto : return views

    IRepositoryBase <|.. RepositoryBase
    ISubscriptionPlanRepository <|.. SubscriptionPlanRepository
    SubscriptionPlanRepository o-- SubscriptionPlan
    ICustomerReviewRepository <|.. CustomerReviewRepository
    CustomerReviewRepository o-- CustomerReview

    IRepositoryBase <|-- ISubscriptionPlanRepository 
    RepositoryBase <|-- SubscriptionPlanRepository
    IRepositoryBase <|-- ICustomerReviewRepository 
    RepositoryBase <|-- CustomerReviewRepository

    DbContext <|--InSyncContext
    RepositoryBase o-- InSyncContext
    SubscriptionPlansController o-- ISubscriptionPlanRepository
    CustomerReviewsController o-- ICustomerReviewRepository



}