@startuml
skinparam classAttributeIconSize 0
skinparam SequenceMessageAlignment center
Title Update Asset Sequence Diagram with Validation

actor "User" as U
boundary "Asset Management Page" as Hp
participant "AssetsController" as ProController
participant "IAssetRepository" as IProRepo
participant "InSyncContext" as ISContext
database "SqlServer" as Db
participant "Mapper" as Mapper

U -> Hp : Enter data and Click button update Asset
activate Hp

Hp -> ProController : Call UpdateAsset(id, updateAssetDto)
activate ProController
ProController -> ProController : Validate ModelState
ProController -> ProController : Check if id matches updateAsset.Id
alt ID mismatch
    ProController -> Hp : Return Message Erorr, 400

    Hp --> U : Notification error   
else ID matches
    ProController -> IProRepo : Check Asset exists by ID
    activate IProRepo
    IProRepo -> ISContext : Get Asset by ID
    activate ISContext
    ISContext -> Db : Fetch Asset data by ID
    activate Db
    Db --> ISContext : Return Asset data
    deactivate Db
    ISContext --> IProRepo : Return Asset
    deactivate ISContext
    IProRepo --> ProController : Return Asset
    deactivate IProRepo

    ProController -> ProController : Check if existingAsset is null
    alt Asset not found
        ProController -> Hp : Return Message Not Found 404
        Hp --> U : Notification error
    else Asset exists
        ProController -> Mapper : Map updateAssetDto to existing Asset
        activate Mapper
        Mapper --> ProController : Return mapped Asset
        deactivate Mapper

        ProController -> IProRepo : Update Asset
        activate IProRepo
        IProRepo -> ISContext : Save updated Asset
        activate ISContext
        ISContext -> Db : Update Asset data in SQL Server
        activate Db
        Db --> ISContext : Return updated Asset
        deactivate Db
        ISContext --> IProRepo : Notify update success
        deactivate ISContext
        IProRepo --> ProController : Return update success
        deactivate IProRepo

        ProController --> Hp : Return update response
        deactivate ProController
        Hp --> U : Show update success message
        deactivate Hp
    end
end

@enduml
