@startuml UpdateScenarioSequenceDiagram
skinparam SequenceMessageAlignment center
Title Update Scenario Sequence Diagram
actor "User" as U
boundary "Screen Udpate Scenario" as Screen
participant "ScenariosController" as SC
participant "IScenarioRepository" as Repo
participant "IMapper" as Mapper

database "SqlServer" as DB

U -> Screen : Submit updated scenario
activate Screen
Screen -> SC : Send UpdateScenario request (id, UpdateScenarioDto)
activate SC


    SC -> SC : Validate ModelState
    alt Invalid ModelState
        SC --> Screen : Show validation errors
        Screen --> U : Show error message
    else Valid ModelState
        SC -> SC : Check if IDs match 
        alt ID mismatch
            SC --> Screen : Return message error id not match
            Screen --> U : Show error message
        else ID matches
            SC -> Repo : Get scenario by ID
            activate Repo
            Repo -> DB : Execute SELECT operation
            activate DB
            DB --> Repo : Return scenario or null
            deactivate DB
            Repo --> SC : Return existing scenario or null
            deactivate Repo

            alt Scenario not found
                SC --> Screen : Return error "Scenario not found"
                Screen --> U : Show error message
            else Scenario found
                SC -> SC : Update DateUpdated
                SC -> Mapper : Map UpdateScenarioDto to existing scenario
                activate Mapper
                Mapper --> SC : Return updated scenario
                deactivate Mapper

                SC -> Repo : Update scenario in repository
                activate Repo
                Repo -> DB : Execute UPDATE operation
                activate DB
                DB --> Repo : Return success or failure
                deactivate DB
                Repo --> SC : Operation result
                deactivate Repo

                alt Update successful 
                    SC --> Screen : Return success message
                    Screen --> U : Show success message
                else Update failed
                    SC --> Screen : Return error ("Error updating scenario")
                    Screen --> U : Show error message
                end
            end
        end
    end


@enduml
