@startuml ResetPasswordSequenceDiagram
skinparam classAttributeIconSize 0
Title Reset Password Sequence Diagram
'Character	Visibility
'-			private
'#			protected
'~			package private
'+			public

'Extension	<|--	Quan hệ mở rộng từ (là extends hoặc implements nhưng ko có annotations trong code)
'Composition	*--	 Quan hệ gắn kết chặt chẽ : part - of
'Aggregation	o--	Quan hệ liên kết giữa hai thực thể : use, has

' Include các file vào trong file để sử dụng'
actor EndUser as u
participant ScreenResetPassword as srp
participant PasswordResetFlow as f
participant PasswordResetProcess as p
participant ResetPasswordRequest as r
participant ResetPasswordCode as c
participant EmailService as e
participant DataContext as su
database DatabaseClerk as db

activate u
u -> srp : enter email and click reset password
activate srp
srp ->f: startPasswordReset()
activate f
f -> r: createResetRequest(email)
activate r
r -> c: generateCode()
activate c
c --> r: resetCode
deactivate c
r -> e: sendResetCodeToUser(user, resetCode)
activate e
e --> r: void
deactivate e
r --> f: return resetCode
deactivate r
f --> srp: resetCode sent to email
deactivate f


srp ->f: enterResetCode(code)
activate f
f -> c: isValid(code)
activate c
c --> f: Boolean (isValid)
deactivate c
alt Mã hợp lệ
    f -> f: Go to the new password entry screen
else Mã không hợp lệ
    f -> u: thông báo lỗi
end
deactivate f


srp ->f: enterNewPassword(newPassword)
activate f
f -> p: resetPassword(su, newPassword)
activate p
p -> su: updatePassword(newPassword)
activate su
su -> db : Update user password into db
activate db
db --> su : update sucessfully
deactivate db
su --> p: Boolean (success)
deactivate su
p --> f: new password has been updated
deactivate p
deactivate f


f --> srp: Password reset process successful
deactivate f

@enduml


