@startuml SetPasswordSequenceDiagram
skinparam classAttributeIconSize 0
Title Set Password Sequence Diagram
'Character	Visibility
'-			private
'#			protected
'~			package private
'+			public

'Extension	<|--	Quan hệ mở rộng từ (là extends hoặc implements nhưng ko có annotations trong code)
'Composition	*--	 Quan hệ gắn kết chặt chẽ : part - of
'Aggregation	o--	Quan hệ liên kết giữa hai thực thể : use, has

' Include các file vào trong file để sử dụng'
actor User as u
participant SceenSetPassword as  ssp
participant AuthenticationService as a
participant UserRepository as ur
participant PasswordValidator as v
database "DataBaseClerk" as dbc

activate u
u --> ssp : enter password to set password and save
activate ssp
ssp -> a: setPassword(userId, newPassword)
activate a
a -> ur: getUserById(userId)
activate ur
ur -> dbc : retrieve user in db
activate dbc
dbc --> ur : user data
deactivate dbc
ur --> a: User

deactivate ur
a -> v: validatePassword(newPassword)
activate v
v --> a: Boolean (isStrong)
deactivate v
a -> ur: updatePassword(userId, hashedPassword)
activate ur
ur -> dbc : update passsword user in db
activate dbc
dbc --> ur : return user success
deactivate dbc
ur --> a: set password success
deactivate ur
a --> ssp: Notification, 200
deactivate a
@enduml


