@startuml
skinparam classAttributeIconSize 0
skinparam SequenceMessageAlignment center
Title Update Page for  Sequence Diagram

actor "Admin" as U
boundary "Document Management Page" as Hp
participant "AdminAuthorizationAttribute" as Author
participant "PagesController" as PageController
participant "IPageRepository" as IPageRepo

participant "Mapper" as Mapper
database "SqlServer" as Db

U -> Hp : Enter Data and Click Update
activate Hp
Hp -> Author : Check permissions
activate Author
alt Request with token role admin
    Author -> PageController : Call UpdatePage()
    activate PageController
    PageController -> PageController : Validate ModelState

    PageController -> Mapper : Map UpdatePageDto to Page
    activate Mapper
    Mapper --> PageController : Return mapped Page
    deactivate Mapper

    PageController -> IPageRepo : Update Page
    activate IPageRepo
    IPageRepo -> Db : Update Page into database
    activate Db
    Db --> IPageRepo : Return update Page data
    deactivate Db
    IPageRepo --> PageController : Return Updated Page
    deactivate IPageRepo

    PageController --> Hp : Return success response 200
    deactivate PageController
    Hp --> U : Show success message
    
else Request with token not role admin
    Author --> Hp : Return Error UnAuthorization
    deactivate Author
    Hp --> U : Notification UnAuthorization
    deactivate Hp
end



@enduml
