@startuml
skinparam classAttributeIconSize 0
class ClassA
class ClassB
interface InterfaceB


ClassA o-- ClassB : Aggregation
ClassA *-- ClassB : Composition

ClassA <--> ClassB : Bidirectional

note left of ClassA : Đây là ghi chú
@enduml
