@startuml DTOs
skinparam classAttributeIconSize 0
skinparam linetype ortho
Title DTOs Class Diagram
'Character	Visibility
'-			private
'#			protected
'~			package private
'+			public

'Extension	<|--	Quan hệ mở rộng từ (là extends hoặc implements nhưng ko có annotations trong code)
'Composition	*--	 Quan hệ gắn kết chặt chẽ : part + of
'Aggregation	o--	Quan hệ liên kết giữa hai thực thể : use, has

package dtos <<Frame>> {
   'Asset DTO'
    !startsub ViewAssetDto
    class ViewAssetDto  <<dto>>  {
        + Id : Guid
        + ProjectId : Guid
        + ProjectName : string
        + AssestName : string
        + Type : string
        + FilePath : string
        + DateCreated : DateTime
        + DateUdpated : DateTime
    }
    !endsub

    !startsub UpdateAssetDto
    class UpdateAssetDto  <<dto>>  {
        + Id : Guid
        + AssestName : string
        + Type : string
    }
    !endsub

    !startsub AddAssetDto
    class AddAssetDto  <<dto>>  {
        + ProjectId : Guid
        + AssestName: string
        + Type : string
        + FilePath : string
    }
    !endsub

    !startsub A
    class ActionAssetResponse  <<dto>>  {
        + Id : Guid
        + Message: string
    }
    !endsub
    'Asset DTO'


    'CustomerReview DTO'
    !startsub ViewCustomerReviewDto
    class ViewCustomerReviewDto <<dto>>   {
        + Id : Guid
        + Name : string
        + ImageUrl : string
        + JobTitle : string
        + Review : string
        + DateCreated : DateTime
        + IsShow : bool
    }
    !endsub

    !startsub AddCustomerReviewDto
    class AddCustomerReviewDto  <<dto>>  {
        + Name : string
        + ImageUrl : string
        + JobTitle : string
        + Review : string
    }
    !endsub

    !startsub UpdateCustomerReviewDto
    class UpdateCustomerReviewDto  <<dto>>  {
        + Id : Guid
        + Name : string
        + ImageUrl : string
        + JobTitle : string
        + Review : string
        + IsShow : bool
    }
    !endsub

    !startsub ActionCustomerReviewResponse
    class ActionCustomerReviewResponse  <<dto>>  {
        + Message : string
        + Id : Guid
    }
    !endsub
    'CustomerReview DTO'

   'CategoryDocuments DTO'
    !startsub ViewCategoryDocumentDto
    class ViewCategoryDocumentDto  <<dto>>  {
    + Id : Guid
    + Title : string
    + Description : string 
    + Order : int
    + DateCreated : DateTime
    + DateUpdated : DateTime 
    + Documents : IEnumerable<ViewDocumentDto>
    }
    !endsub

    !startsub UpdateCategoryDocumentDto
    class UpdateCategoryDocumentDto  <<dto>>  {
    + Id : Guid
    + Title : string
    + Order : int
    + Description : string 
    }
    !endsub


    !startsub AddCategoryDocumentDto
    class AddCategoryDocumentDto  <<dto>>  {
    + Title : string
    + Order : int
    + Description : string 
    }
    !endsub


    !startsub ActionCategoryDocumentResponse
    class ActionCategoryDocumentResponse <<dto>>   {
    + Message : string
    + Id : Guid
    }
    !endsub
    'CategoryDocuments DTO'

    'Documents DTO'
    
    !startsub ViewDocumentDto
    class ViewDocumentDto  <<dto>>  {
    + Id : Guid
    + Slug : string
    + Title : string
    + Content : string 
    + Note : string 
    + Order : int
    + DateCreated : DateTime
    + DateUpdated : DateTime 
    + CategoryId : Guid
    + CategoryName : string
    }
    !endsub


    !startsub UpdateDocumentDto
    class UpdateDocumentDto  <<dto>>  {
    + Id : Guid
    + Slug : string
    + Title : string
    + Content : string 
    + Note : string 
    + Order : int
    + CategoryId : Guid
    }
    !endsub

    !startsub AddDocumentDto
    class AddDocumentDto  <<dto>>  {
    + Slug : string
    + Title : string
    + Content : string 
    + Note : string 
    + Order : int
    + CategoryId : Guid
    }
    !endsub

    !startsub ActionDocumentResponse
    class ActionDocumentResponse  <<dto>>  {
    + Message : string
    + Id : Guid
    }
    !endsub
    'Documents DTO'

    'Pages DTO'

    !startsub ViewPageDto
    class ViewPageDto  <<dto>>  {
    + Id : Guid
    + Slug : string
    + Title : string
    + Content : string 
    + Note : string 
    + DateCreated : DateTime 
    + DateUpdated : DateTime 
    }
    !endsub


    !startsub UpdatePageDto
    class UpdatePageDto  <<dto>>  {
    + Id : Guid
    + Slug : string
    + Title : string
    + Content : string 
    + Note : string 
    }
    !endsub

    !startsub AddPageDto
    class AddPageDto  <<dto>>  {
    + Slug : string
    + Title : string
    + Content : string 
    + Note : string 
    }
    !endsub

    !startsub ActionPageResponse
    class ActionPageResponse  <<dto>>  {
    + Message : string
    + Id : Guid
    }
    !endsub
    'Page DTO'

    'Project Dto
    !startsub ViewProjectDto
    class ViewProjectDto  <<dto>>  {
        + Id : Guid
        + ProjectName : string
        + Description : string 
        + UserId : Guid
        + displayName : string
        + DateCreated : DateTime
        + DateUpdated : DateTime
        + IsPublish : bool
    }
    !endsub

    !startsub AddProjectDto
    class AddProjectDto  <<dto>>  {
        + ProjectName : string
        + Description : string
        + UserId : Guid
        + IsPublish : bool
    }
    !endsub

    !startsub AddProjectClerkDto
    class AddProjectClerkDto <<dto>>   {
        + ProjectName : string
        + Description : string
        + UserIdClerk : string
        + IsPublish : bool
    }
    !endsub

    !startsub UpdateProjectDto
    class UpdateProjectDto  <<dto>>  {
        + Id : Guid
        + ProjectName : string
        + Description : string
        + IsPublish : bool
    }
    !endsub

    !startsub ActionProjectResponse
    class ActionProjectResponse  <<dto>>  {
        + Message : string
        + Id : Guid
    }
    !endsub
    'ProjectDto'

    'Response Paging'
    !startsub ResponsePaging
    class ResponsePaging  <<dto>>  {
        + data : T
        + totalOfData : int
    }
    !endsub
    'Response Paging'

    'Scenario Dto
    !startsub ViewScenarioDto
    class ViewScenarioDto  <<dto>>  {
        + Id : Guid
        + ProjectId : Guid
        + ProjectName : string
        + Title : string
        + Description : string 
        + CreatedAt : DateTime
        + UpdatedAt : DateTime 
        + StepsWeb : string 
        + StepsAndroid : string 
        + IsFavorites : bool 
        + ImageUrl : string 
        + AuthorId : string
        + AuthorIdGuid: Guid
        + AuthorName : string
    }
    !endsub

    !startsub AddScenarioDto
    class AddScenarioDto  <<dto>>  {
        + ProjectId : Guid
        + ScenarioName : string
        + Description : string 
        + StepsWeb : string 
        + StepsAndroid : string 
        + IsFavorites : bool 
        + ImageUrl : string 
        + CreatedBy : Guid
    }
    !endsub

    !startsub AddScenarioUserClerkDto
    class AddScenarioUserClerkDto  <<dto>>  {
        + ProjectId : Guid
        + ScenarioName : string
        + Description : string 
        + StepsWeb : string 
        + StepsAndroid : string 
        + IsFavorites : bool 
        + ImageUrl : string 
        + UserIdClerk : string
    }
    !endsub

    !startsub UpdateScenarioDto
    class UpdateScenarioDto <<dto>>   {
        + Id : Guid
        + ScenarioName : string
        + Description : string 
        + StepsWeb : string 
        + StepsAndroid : string 
        + IsFavorites : bool 
        + ImageUrl : string 
    }
    !endsub

    !startsub UpdateRenameScenarioDto
    class UpdateRenameScenarioDto  <<dto>>  {
        + Id : Guid
        + ScenarioName : string
    }
    !endsub

    !startsub ActionScenarioResponse
    class ActionScenarioResponse  <<dto>>  {
        + Message : string
        + Id : Guid
    }
    !endsub

    'Scenario DTO'

    'Subscription Plan Dtos
    !startsub ViewSubscriptionPlanDto
    class ViewSubscriptionPlanDto <<dto>>   {
        + Id : Guid
        + SubscriptionsName : string
        + Status : bool
        + Price : decimal
        + UserId : Guid
        + UserName : string
        + Content : string
        + DateCreated : DateTime
        + DateUpdated : DateTime 
        + MaxProjects : int  
        + MaxAssets : long 
        + MaxScenarios : int 
        + MaxUsersAccess : int 
        + StorageLimit : long 
        + SupportLevel : string 
        + CustomFeaturesDescription : string 
        + DataRetentionPeriod : long 
        + PrioritySupport : bool 
        + MonthlyReporting : bool 
    }
    !endsub

    !startsub AddSubscriptionPlanDto
    class AddSubscriptionPlanDto  <<dto>>  {
        + SubscriptionsName : string
        + Status : bool
        + Price : decimal
        + UserId : Guid
        + Content : string
        + MaxProjects : int 
        + MaxAssets : long 
        + MaxScenarios : int 
        + MaxUsersAccess : int 
        + StorageLimit : long 
        + SupportLevel : string 
        + CustomFeaturesDescription : string 
        + DataRetentionPeriod : long 
        + PrioritySupport : bool 
        + MonthlyReporting : bool 
    }
    !endsub

    !startsub AddSubscriptionPlanUserClerkDto
    class AddSubscriptionPlanUserClerkDto  <<dto>>  {
        + SubscriptionsName : string
        + Status : bool
        + Price : decimal
        + UserIdClerk : string
        + Content : string
        + MaxProjects : int 
        + MaxAssets : long 
        + MaxScenarios : int 
        + MaxUsersAccess : int 
        + StorageLimit : long 
        + SupportLevel : string 
        + CustomFeaturesDescription : string 
        + DataRetentionPeriod : long 
        + PrioritySupport : bool 
        + MonthlyReporting : bool 
    }
    !endsub

    !startsub UpdateSubscriptionPlanDto
    class UpdateSubscriptionPlanDto  <<dto>>  {
        + Id : Guid
        + SubscriptionsName : string
        + Status : bool
        + Price : decimal
        + Content : string
        + MaxProjects : int 
        + MaxAssets : long 
        + MaxScenarios : int 
        + MaxUsersAccess : int 
        + StorageLimit : long 
        + SupportLevel : string 
        + CustomFeaturesDescription : string 
        + DataRetentionPeriod : long 
        + PrioritySupport : bool 
        + MonthlyReporting : bool 
    }
    !endsub

    !startsub ActionSubscriptionPlanResponse
    class ActionSubscriptionPlanResponse  <<dto>>  {
        + Message : string
        + Id : Guid
    }
    !endsub
    'SubscriptionPlan DTo'

    'Tutorial Dtos
    !startsub ViewTutorialDto
    class ViewTutorialDto  <<dto>>  {
        + Id : Guid
        + Title : string
        + Content : string
        + DateCreated : DateTime
        + DateUpdated : DateTime
        + IsShow : bool
        + Order : long
    }
    !endsub


    'User Dtos
    !startsub Data
    class Data  <<dto>>  {
        + Birthday : string
        + Created_At : long
        + Email_Addresses : EmailAddresses[] 
        + First_Name : string 
        + Gender : string 
        + Id : string 
        + Image_Url : string 
        + Last_Name : string 
        + Last_Sign_In_At : long 
        + Object : string 
        + Password_Enabled : bool 
        + Phone_Numbers : string[] 
        + Primary_Email_Address_Id : string 
        + Primary_Phone_Number_Id : string 
        + Primary_Web3_Wallet_Id : string 
        + Private_Metadata : Dictionary<string, object> 
        + Profile_Image_Url : string 
        + Public_Metadata : Dictionary<string,object> 
        + Two_Factor_Enabled : bool 
        + Unsafe_Metadata : Dictionary 
        + Updated_At : long 
        + Username : object 
        + Web3_Wallets : string[] 
    }
    !endsub

    !startsub EmailAddresses
    class EmailAddresses <<dto>>   {
        + Email_Address : string
        + Id : string
        + Linked_To : object[]
        + Object : string
        + Verification : Verification
    }
    !endsub

    !startsub Verification
    class Verification  <<dto>>  {
        + Status : string
        + Strategy : string
    }
    !endsub

    !startsub CreateUserDto
    class CreateUserDto  <<dto>>  {
        + Data : Data
        + Object : string
        + Type : string
    }
    !endsub

    !startsub UpdateUserDto
    class UpdateUserDto  <<dto>>  {
        + Data : Data
        + Object : string
        + Type : string
    }
    !endsub

    !startsub ActionUserResponse
    class ActionUserResponse  <<dto>>  {
        + Message : string
        + Id : Guid
    }
    !endsub

    'Relationships
    Data "1" --> "*" EmailAddresses
    EmailAddresses "1" --> "1" Verification
    CreateUserDto "1" --> "1" Data
    UpdateUserDto "1" --> "1" Data

'User Subscription Dtos
    !startsub ViewUserSubscriptionDto
    class ViewUserSubscriptionDto  <<dto>>  {
        + Id : Guid
        + SubscriptionPlanId : Guid
        + SubscriptionPlanName : string
        + UserId : Guid
        + UserName : string
        + StripeCurrentPeriodEnd : DateTime
        + StripeCustomerId : string
        + StripeSubscriptionId : string
        + StripePriceId : string
        + DateCreated : DateTime
    }
    !endsub

    !startsub AddUserSubscriptionDto
    class AddUserSubscriptionDto   <<dto>> {
        + SubscriptionPlanId : Guid
        + UserId : Guid
        + StripeCurrentPeriodEnd : DateTime
        + StripeCustomerId : string
        + StripeSubscriptionId : string
        + StripePriceId : string
    }
    !endsub

    !startsub AddUserSubscriptionUserClerkDto
    class AddUserSubscriptionUserClerkDto  <<dto>>  {
        + SubscriptionPlanId : Guid
        + UserIdClerk : string
        + StripeCurrentPeriodEnd : DateTime
        + StripeCustomerId : string
        + StripeSubscriptionId : string
        + StripePriceId : string
    }
    !endsub

    !startsub UpdateUserSubscriptionDto
    class UpdateUserSubscriptionDto  <<dto>>  {
        + Id : Guid
        + SubscriptionPlanId : Guid
        + StripeCurrentPeriodEnd : DateTime
        + StripeCustomerId : string
        + StripeSubscriptionId : string
        + StripePriceId : string
    }
    !endsub

    !startsub ActionUserSubscriptionResponse
    class ActionUserSubscriptionResponse  <<dto>>  {
        + Message : string
        + Id : Guid
    }
    !endsub

}

@enduml