@startuml Models
skinparam classAttributeIconSize 0
Title Models Class Diagram
'Character	Visibility
'-			private
'#			protected
'~			package private
'+			public

'Extension	<|--	Quan hệ mở rộng từ (là extends hoặc implements nhưng ko có annotations trong code)
'Composition	*--	 Quan hệ gắn kết chặt chẽ : part - of
'Aggregation	o--	Quan hệ liên kết giữa hai thực thể : use, has


package pkgModels <<Frame>> {

    !startsub Asset
    class Asset    {
        + Id : Guid
        + ProjectId : Guid
        + AssestName : string
        + Type : string <<nullable>>
        + FilePath : string
        + DateCreated : DateTime
        + DateUdpated : DateTime <<nullable>>
        + Project : Project
    }
    !endsub

    !startsub CategoryDocument
    class CategoryDocument  {
        + CategoryDocument()
        + Id : Guid
        + Title : string
        + Description : string<<nullable>>
        + DateCreated : DateTime
        + DateUdpated : DateTime<<nullable>>
        + Documents : ICollection<Document>
    }
    !endsub

    !startsub Document
    class Document  {
        + Id : Guid
        + Slug : string
        + Title : string
        + Content : string <<nullable>>
        + Note : string <<nullable>>
        + Order : int
        + DateCreated : DateTime
        + DateUdpated : DateTime <<nullable>>
        + Documents : ICollection<Document>
        + CategoryId : Guid
        + Category : CategoryDocument
    }
    !endsub

    !startsub CustomerReview
    class CustomerReview    {
        + Id : Guid
        + Name : string
        + ImageUrl : string<<nullable>>
        + JobTitle : string
        + Review : string
        + DateCreated : DateTime
        + IsShow : bool
    }
    !endsub

    !startsub Page
    class Page   {
        + Id : Guid
        + Slug : string
        + Title : string
        + Content : string<<nullable>>
        + Note : string<<nullable>>
        + DateCreated : DateTime
        + DateUdpated : DateTime<<nullable>>
    }
    !endsub

    !startsub Project
    class Project    {
        + Project()

        + Id : Guid
        + ProjectName : string
        + Description : string<<nullable>>
        + UserId : Guid
        + DateCreated : DateTime
        + DateUpdated : DateTime<<nullable>>
        + IsPublish : bool
        + User : User;
        + Assets : ICollection<Asset>
        + Scenarios : ICollection<Scenario>
    }
    !endsub

    !startsub Scenario
    class Scenario    {
        + Id : Guid
        + ProjectId : Guid
        + ScenarioName : string
        + Description : string<<nullable>>
        + DateCreated : DateTime
        + DateUpdated : DateTime<<nullable>>
        + StepsWeb : string<<nullable>>
        + StepsAndroid : string<<nullable>>
        + IsFavorites : bool<<nullable>>
        + ImageUrl : string<<nullable>>
        + CreatedBy : Guid
        + CreatedByNavigation : User
        + Project : Project
    }
    !endsub

    !startsub SubscriptionPlan
    class SubscriptionPlan    {
        + SubscriptionPlan()
        + Id : Guid
        + SubscriptionsName : string
        + Status : bool
        + Price : decimal
        + UserId : Guid
        + Content : string
        + DateCreated : DateTime
        + DateUpdated : DateTime<<nullable>>
        + MaxProjects : int<<nullable>>
        + MaxAssets : long<<nullable>>
        + MaxScenarios : int<<nullable>>
        + MaxUsersAccess : int<<nullable>>
        + StorageLimit : long<<nullable>>
        + SupportLevel : string<<nullable>>
        + CustomFeaturesDescription : string<<nullable>>
        + DataRetentionPeriod : long<<nullable>>
        + PrioritySupport : bool<<nullable>>
        + MonthlyReporting : bool<<nullable>>
        + User : User
        + UserSubscriptions : ICollection<UserSubscription>
    }
    !endsub

    !startsub User
    class User    {
        + User()

        + Id : Guid
        + UserIdClerk : string<<nullable>>
        + UserName : string
        + PasswordHash : string<<nullable>>
        + Email : string
        + DisplayName : string<<nullable>>
        + EmailConfirmed : bool<<nullable>>
        + PhoneNumber : string<<nullable>>
        + LockoutEnd : DateTime<<nullable>>
        + LockoutEnable : bool<<nullable>>
        + AccessFailCount : long
        + ImageUrl : string<<nullable>>
        + Dob : DateTime<<nullable>>
        + Address : string<<nullable>>
        + DateCreated : DateTime
        + DateUpdated : DateTime<<nullable>>
        + StatusUser : int
        + Role : string<<nullable>>
        + Projects : ICollection<Project>
        + Scenarios : ICollection<Scenario>
        + SubscriptionPlans : ICollection<SubscriptionPlan>
        + UserSubscriptions : ICollection<UserSubscription>
    }
    !endsub

    !startsub UserSubscription
    class UserSubscription    {
        + Id : Guid
        + SubscriptionPlanId : Guid
        + UserId : Guid
        + StripeCurrentPeriodEnd : DateTime
        + StripeCustomerId : string
        + StripeSubscriptionId : string
        + StripePriceId : string
        + DateCreated : DateTime
        + SubscriptionPlan : SubscriptionPlan
        + User : User
    }
    !endsub

    ' Relationships
    User "1" --> "*" Project : creates
    

    User "1" --> "*" Scenario : creates
    
    User "1" --> "0--*" SubscriptionPlan : admin creates
   

    User "1" --> "0--*" UserSubscription : has
   

    Project "1" --> "0..*" Asset : contains

    Project "1" --> "0..*" Scenario : contains
    

    CategoryDocument "1" -->"0..*" Document : contains

    
    SubscriptionPlan "1" --> "0..*" UserSubscription : has
   
}
@enduml