@startuml Repositorys
skinparam classAttributeIconSize 0
skinparam classAttributeIconSize 0
Title Repository Class Diagram

'Character	Visibility
'-			private
'#			protected
'~			package private
'+			public

'Extension	<|--	Quan hệ mở rộng từ (là extends hoặc implements nhưng ko có annotations trong code)
'Composition	*--	 Quan hệ gắn kết chặt chẽ : part - of
'Aggregation	o--	Quan hệ liên kết giữa hai thực thể : use, has
'Association	||	Quan hệ liên kết giữa hai thực thể : use, has, contains
'Inheritance	<|--	Quan hệ mở rộng từ (là extends hoặc implements nhưng
'ko có annotations trong code)'


package pkgRepositorys <<Frame>>{
!startsub DbContext
abstract DbContext {
}
!endsub

!startsub InSyncContext
class InSyncContext {
    + InSyncContext()
    + InSyncContext(options : DbContextOptions<InSyncContext>)
    + Assets : DbSet<Asset>
    + CategoryDocuments : DbSet<CategoryDocument>
    + CustomerReviews : DbSet<CustomerReview>
    + Documents : DbSet<Document>
    + Pages : DbSet<Page>
    + Projects : DbSet<Project>
    + Scenarios : DbSet<Scenario>
    + SubscriptionPlans : DbSet<SubscriptionPlan>
    + Users : DbSet<User>
    + UserSubscriptions : DbSet<UserSubscription>
    # OnConfiguring(optionsBuilder : DbContextOptionsBuilder)
    - OnModelCreatingPartial(modelBuilder:ModelBuilder )
}
!endsub

    
!startsub IRepositoryBase
interface IRepositoryBase<T> {
    + Add(entity : T) : Task<T>
    + Update(entity : T) : Task
    + Delete(entity : T) : Task<T>
    + DeleteMulti(where : Expression<Func<T, bool>>) : Task
    + GetSingleByCondition(expression : Expression<Func<T, bool>>, 
      includes : string[] <<nullable>>) : Task<T>
    + GetAll(includes : string[] <<nullable>>) : IEnumerable<T>
    + GetMulti(predicate : Expression<Func<T, bool>>, 
      includes : string[] <<nullable>>) : IEnumerable<T>
    + GetMultiPaging(filter : Expression<Func<T, bool>>, 
      out total : int, 
      index : int = 0, 
      size : int = 50, 
      includes : string[] <<nullable>>) : IEnumerable<T>
    + CountAsync(where : Expression<Func<T, bool>>) : Task<int>
    + CheckContainsAsync(predicate : Expression<Func<T, bool>>) : Task<bool>
}

!endsub

!startsub RepositoryBase

class RepositoryBase<T>    {
    # _context : InSyncContext
    - disposed : bool
    + RepositoryBase(context : InSyncContext)
    + Add(entity : T) : Task<T>
    + Update(entity : T) : Task
    + Delete(entity : T) : Task<T>
    + DeleteMulti(where : Expression<Func<T, bool>>) : Task
    + GetSingleByCondition(expression : Expression<Func<T, bool>>, 
      includes : string[] <<nullable>>) : Task<T>
    + GetAll(includes : string[] <<nullable>>) : IEnumerable<T>
    + GetMulti(predicate : Expression<Func<T, bool>>, 
      includes : string[] <<nullable>>) : IEnumerable<T>
    + GetMultiPaging(filter : Expression<Func<T, bool>>, 
      out total : int, 
      index : int = 0, 
      size : int = 50, 
      includes : string[] <<nullable>>) : IEnumerable<T>
    + CountAsync(where : Expression<Func<T, bool>>) : Task<int>
    + CheckContainsAsync(predicate : Expression<Func<T, bool>>) : Task<bool>
    + Dispose() : void
    - Dispose(disposing : bool) : void
}
!endsub



!startsub IAssetRepository


!endsub
 
!startsub AssetRepository
interface IAssetRepository    {
    // Inherits from IRepositoryBase<Asset>
}
class AssetRepository    {
    - _context : InSyncContext
    + AssetRepository(context : InSyncContext)
    // Inherits from RepositoryBase<Asset>
}

!endsub


!startsub ICategoryDocumentRepository
interface ICategoryDocumentRepository    {
    + DeleteCategoryDocument(id : Guid) : Task
    // Inherits from IRepositoryBase<CategoryDocument>
}
!endsub

!startsub CategoryDocumentRepository
class CategoryDocumentRepository    {
    - _context : InSyncContext
    + CategoryDocumentRepository(context : InSyncContext)
    + DeleteCategoryDocument(id : Guid) : Task
    // Inherits from RepositoryBase<CategoryDocument>
}
!endsub


!startsub ICustomerReviewRepository
interface ICustomerReviewRepository    {
    // Inherits from IRepositoryBase<CustomerReview>
}
!endsub

!startsub CustomerReviewRepository
class CustomerReviewRepository    {
    - _context : InSyncContext
    + CustomerReviewRepository(context : InSyncContext)
    // Inherits from RepositoryBase<CustomerReview>
}
!endsub


!startsub IDocumentRepository
interface IDocumentRepository    {
    // Inherits from IRepositoryBase<Document>
}
!endsub

!startsub DocumentRepository
class DocumentRepository    {
    - _context : InSyncContext
    + DocumentRepository(context : InSyncContext)
    // Inherits from RepositoryBase<Document>
}
!endsub


!startsub IPageRepository
interface IPageRepository    {
    // Inherits from IRepositoryBase<Page>
}
!endsub

!startsub PageRepository
class PageRepository    {
    - _context : InSyncContext
    + PageRepository(context : InSyncContext)
    // Inherits from RepositoryBase<Page>
}
!endsub


!startsub IProjectRepository
interface IProjectRepository    {
    + DeleteProject(id : Guid) : Task
    // Inherits from IRepositoryBase<Project>
}
!endsub

!startsub ProjectRepository
class ProjectRepository    {
    - _context : InSyncContext
    + ProjectRepository(context : InSyncContext)
    + DeleteProject(id : Guid) : Task
    // Inherits from RepositoryBase<Project>
}
!endsub


!startsub IScenarioRepository
interface IScenarioRepository    {
    // Inherits from IRepositoryBase<Scenario>
}
!endsub

!startsub ScenarioRepository
class ScenarioRepository    {
    - _context : InSyncContext
    + ScenarioRepository(context : InSyncContext)
    // Inherits from RepositoryBase<Scenario>
}
!endsub



!startsub ISubscriptionPlanRepository
interface ISubscriptionPlanRepository    {
    + DeleteSubscriptionPlan(id : Guid) : Task
    // Inherits from IRepositoryBase<SubscriptionPlan>
}
!endsub

!startsub SubscriptionPlanRepository
class SubscriptionPlanRepository    {
    - _context : InSyncContext
    + SubscriptionPlanRepository(context : InSyncContext)
    + DeleteSubscriptionPlan(id : Guid) : Task
    // Inherits from RepositoryBase<SubscriptionPlan>
}
!endsub

!startsub IUserRepository
interface IUserRepository    {
    // Inherits from IRepositoryBase<User>
}
!endsub

!startsub UserRepository
class UserRepository    {
    - _context : InSyncContext
    + UserRepository(context : InSyncContext)
    // Inherits from RepositoryBase<User>
}
!endsub


!startsub IUserSubscriptionRepository
interface IUserSubscriptionRepository    {
    // Inherits from IRepositoryBase<UserSubscription>
}
!endsub

!startsub UserSubscriptionRepository
class UserSubscriptionRepository    {
    - _context : InSyncContext
    + UserRepository(context : InSyncContext)
    // Inherits from RepositoryBase<UserSubscription>
}
!endsub
}
@enduml
