@startuml Hello World

Title SignIn Class Diagram
'Character	Visibility
'-			private
'#			protected
'~			package private
'+			public

'Extension	<|--	Quan hệ mở rộng từ (là extends hoặc implements nhưng ko có annotations trong code)
'Composition	*--	 Quan hệ gắn kết chặt chẽ : part - of
'Aggregation	o--	Quan hệ liên kết giữa hai thực thể : use, has

'Lưu ý, do mỗi Repository , IRepository đều không có gì bên trong nên khi tạo diagram mới thì chỉ cần copy lại rồi đổi tên


package pkgSignin <<Frame>> {
        !includesub ControllersClassDiagram.plantuml!UsersController
        !includesub ControllersClassDiagram.plantuml!ControllerBase

        class UserRepository <<(C,orchid) repository>>
        interface IUserRepository <<(I,#FF7700) repository>>
        !includesub ModelsClassDiagram.plantuml!User
        class clerk-web-hook-create <<(A, yellow) middleware>>

        !includesub DtosClassDiagram.plantuml!CreateUserDto
        

        class UserRepository implements IUserRepository
        class UsersController extends ControllerBase
        UsersController o-- IUserRepository
        UsersController o-- CreateUserDto 
        UserRepository o-- User
        "clerk-web-hook-create" -- UsersController
}

@enduml