@startuml DeleteSchedule
skinparam classAttributeIconSize 0
skinparam linetype ortho

skinparam BackgroundColor #ffffff
skinparam class {
    BackgroundColor #c6f8ff
    BorderColor #000000
}

skinparam package {
    BackgroundColor #ffffff
    BorderColor #000000
}

package pkgDeleteSchedule <<Frame>>{

 
        class ScheduleView {
            + displaySchedules(): void
            + deleteSchedule(scheduleId: Long): void
        }

        class ScheduleController {
            - schedules: List<DriverJourney>
            + fetchSchedules(): void
            + deleteSchedule(scheduleId: Long): void
        }
    
        class DriverJourneyController {
            + deleteSchedule(driverJourneyIdRequestDto: DriverJourneyIdRequestDto): ResponseEntity<ResponseWrapper<DriverJourneyResponseDto>>
        }
  
        class DriverJourneyService {
            + deleteSchedule(scheduleId: Long): DriverJourneyResponseDto
        }

        class DriverJourneyRepository {
            + findById(scheduleId: Long): Optional<DriverJourney>
            + save(driverJourney: DriverJourney): DriverJourney
        }
 
        class DriverJourneyIdRequestDto {
            - scheduleId: Long
        }

        class DriverJourneyResponseDto {
            - journeyId: Long
            - startLocation: String
            - endLocation: String
            - departureTime: LocalDateTime
            - vehicleType: String
            - specialNotes: String
        }

        class ResponseWrapper<T> {
            - responseCode: int
            - message: String
            - data: T
        }
 
        class DriverJourney {
            - journeyId: long
            - user: User
            - startLocation: Location
            - endLocation: Location
            - departureTime: LocalDateTime
            - vehicleType: String
            - specialNotes: String
        }

        class User {
            - userId: long
            - name: String
            - phoneNumber: String
            - password: String
            - profilePicture: byte[]
            - isActive: boolean
            - isLocked: boolean
            - createdDate: LocalDateTime
            - tokenVersion: long
        }

        class Location {
            - locationId: long
            - address: String
            - latitude: double
            - longitude: double
        }
    

    ScheduleView --> ScheduleController
    ScheduleController --> DriverJourneyController
    DriverJourneyController --> DriverJourneyService
    DriverJourneyService --> DriverJourneyRepository
    DriverJourneyService --> DriverJourneyIdRequestDto
    DriverJourneyService --> DriverJourneyResponseDto
    DriverJourneyController --> ResponseWrapper
    DriverJourneyService --> DriverJourney
    DriverJourneyRepository --> DriverJourney
    DriverJourney --> User
    DriverJourney --> Location

}

@enduml